channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
  - pip
  - adapterremoval>=2.2.0
  - samtools>=1.3.0
  - picard>=1.137
  - bowtie2>=2.3.0
  - bwa>=0.7.15
  - mapdamage2>=2.2.1
  - r-base
  - r-rcpp
  - r-rcppgsl
  - r-gam
  - r-inline
  - pip:
    - paleomix==1.3.2
