channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.7,<3.10
  - pip
  - adapterremoval>=2.3,<3
  - samtools>=1.6,<2
  - picard>=2.10,<3
  - bowtie2>=2.3,<2.5
  - bwa>=0.7.15,<0.8
  - mapDamage2>=2.2.1,<2.3
  - r-base
  - r-rcpp
  - r-rcppgsl
  - r-gam
  - r-inline
  - pip:
      - paleomix==1.3.10
